# Pytorch自动微分

In [1]:
import torch

## 创建一个张量,设置requires_grad=True 来跟踪与他相关的计算

In [15]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


## 执行一次操作,例如+2

In [16]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y 作为操作结果被创建,所以它有grad_fn

In [17]:
print(y.grad_fn)

针对y做更多的操作:

In [18]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.require_grade(...)会改变张量的require_grad 标记,如果没有提供标记参数,收入的默认标记为False.

In [19]:
a = torch.ones(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度

我们现在后向传播,因为输出包含了一个标量,out.backword() 等同于 out.backward(torch.tensor(1.))

In [20]:
out.backward()

打印梯度d(out)/dx

In [21]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


现在让我们来看一个雅可比向量积的例子