In [10]:
from __future__ import print_function
import torch

# Tensor 张量

## 构造一个5*3矩阵,不初始化

In [11]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29, -6.4337e-20],
        [ 8.5920e+09,  1.1210e-44, -2.5244e-29],
        [-6.4159e-20, -1.5849e+29,  1.5723e-01],
        [ 8.4932e-01,  2.8396e-01,  6.1079e-01],
        [ 3.3894e-01,  6.1449e-01,  1.5548e-01]])


## 构造一个随机初始化矩阵:

In [12]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1591, 0.1795, 0.2249],
        [0.7459, 0.9969, 0.1731],
        [0.2635, 0.1341, 0.2466],
        [0.3962, 0.9954, 0.6061],
        [0.3575, 0.9394, 0.0016]])


## 构造一个矩阵全为0,而且数据类型是long

In [13]:
x = torch.zeros(5, 3 ,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 构造一个张量,直接使用数据

In [14]:
x = torch.tensor([5.5 ,3])
print(x)

tensor([5.5000, 3.0000])


## 创建一个tensor基于已经存在的tensor

In [16]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.rand_like(x,dtype=torch.float)
print(x)
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.8616, 0.5383, 0.6691],
        [0.8226, 0.6372, 0.2762],
        [0.3094, 0.1324, 0.9990],
        [0.7503, 0.4711, 0.6660],
        [0.5383, 0.4258, 0.8731]])


## 获取他的维度信息

In [19]:
print(x.size())

torch.Size([5, 3])


# 操作

## 加法: 方式一

In [20]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tensor([[1,1,1],[1,1,1],[1,1,1]])
y = a + b
print(y)

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])


## 加法:方式二 提供一个tensor作为参数

In [21]:
z = torch.add(a,b)
print(z)

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])


## 加法:方式三 in-place

In [25]:
d = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
e = torch.tensor([[1,1,1],[1,1,1],[1,1,1]])
d.add_(e)
print(d)

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])


注意: 任何使张量会发生变化的操作都有一个前缀'_'

## 使用Numpy操作

In [27]:
## 打印下标为1的列
print(a[:,1])

tensor([2, 5, 8])


In [28]:
## 打印下标为1的行
print(a[1,:])

tensor([4, 5, 6])


## 改变一个tensor的大小或者形状

In [37]:
## 注意,仅改变形状
g = torch.randn(4,4)
print(g)

h = g.view(16)
print(h)

g = torch.randn(4,4)
i = g.view(2,8)
print(i)


tensor([[-0.1556,  0.0234,  0.1663,  0.8174],
        [-0.1728, -0.8680,  0.0983,  0.5854],
        [-0.2973,  0.7188, -0.6855, -1.7135],
        [ 2.0269, -0.0636, -0.2445, -0.7971]])
tensor([-0.1556,  0.0234,  0.1663,  0.8174, -0.1728, -0.8680,  0.0983,  0.5854,
        -0.2973,  0.7188, -0.6855, -1.7135,  2.0269, -0.0636, -0.2445, -0.7971])
tensor([[-0.2835,  1.0742, -1.0645,  0.0264, -0.3054,  0.4001, -0.1364, -0.6867],
        [-0.2792, -2.3101,  0.7951, -1.8889,  1.9994, -1.0867, -0.0682,  0.1978]])


## 用.item来获取value

In [41]:
j = torch.rand([1])
print(j.item())

0.2749972939491272
